const $=id=>document.getElementById(id);
const API='https://ttvlgfzvgjcbomdlddbn.supabase.co/functions/v1/noop-db-viewer';
const TABLES=['device','pairedDevice','dayOwnership','hrSample','ppgHrSample','rrInterval','event','battery','spo2Sample','skinTempSample','stepSample','sleepStateSample','respSample','gravitySample','dailyMetric','sleepSession','metricSeries','labMarker','journal','workout','dismissedWorkout','dismissedSleep','appleDaily','liveSession'];
const STATE_META={
  SLEEP:{label:'СОН',cls:'sleep'},REST:{label:'ВІДПОЧИНОК',cls:'rest'},MOVEMENT:{label:'РУХ',cls:'move'},RECOVERY:{label:'ПІСЛЯ РУХУ',cls:'recovery'},AUTONOMIC_LOAD:{label:'AUTONOMIC LOAD',cls:'load'},UNKNOWN:{label:'UNKNOWN',cls:'unknown'}
};
let period='today',allHr=[],eventType='note',stateRows=[],stateEvents=[],stateModel={movementThreshold:.02,baselineHr:null,baselineRmssd:null};

$('refreshBtn').onclick=load;
$('dbNav').onclick=()=>{$('database').classList.toggle('hidden');$('database').scrollIntoView({behavior:'smooth'})};
$('closeViewer').onclick=()=>$('viewer').classList.add('hidden');
$('quickJournal').onclick=openJournal;$('journalNav').onclick=openJournal;$('closeJournal').onclick=()=>$('journalView').classList.add('hidden');
document.querySelectorAll('.quick-types button').forEach(b=>b.onclick=()=>{eventType=b.dataset.type;document.querySelectorAll('.quick-types button').forEach(x=>x.classList.toggle('active',x===b))});
document.querySelectorAll('[data-marker]').forEach(b=>b.onclick=()=>saveQuickMarker(b.dataset.marker,b.dataset.markerType));
$('saveEvent').onclick=saveEvent;$('voiceBtn').onclick=startVoice;
$('eventPhoto').onchange=()=>{$('journalMsg').textContent=$('eventPhoto').files?.[0]?'Фото вибрано. Аналіз фото додамо наступним етапом; зараз збережи опис події.':''};
document.querySelectorAll('#periods button').forEach(b=>b.onclick=async()=>{period=b.dataset.period;document.querySelectorAll('#periods button').forEach(x=>x.classList.toggle('active',x===b));await Promise.all([loadHr(),loadState(),loadStateEvents()]);renderPulse();renderStateLab();updateStatus()});
load();setInterval(load,15000);

async function api(p,opt={}){const u=new URL(API);Object.entries(p).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u,{cache:'no-store',...opt});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();if(d&&d.error)throw Error(d.error);return d}
function epochMs(v){const n=Number(v);if(!Number.isFinite(n))return 0;return n<1e12?n*1000:n}
function windowStart(){const now=Date.now();if(period==='today'){const d=new Date();d.setHours(0,0,0,0);return d.getTime()}return now-(+period)*3600000}

async function openJournal(){$('journalView').classList.remove('hidden');await loadTimeline()}
async function saveQuickMarker(title,type){$('journalMsg').textContent='Записую '+title+'…';try{await api({api:'timeline'},{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,event_type:type,input_mode:'marker',details:{protocol:'state-engine-calibration-v0'}})});$('journalMsg').textContent='✓ '+title+' · '+new Date().toLocaleTimeString('uk-UA',{hour:'2-digit',minute:'2-digit',second:'2-digit'});await Promise.all([loadTimeline(),loadStateEvents()]);renderStateLab()}catch(e){$('journalMsg').textContent='Помилка: '+e.message}}
async function saveEvent(){const title=$('eventText').value.trim();if(!title)return $('journalMsg').textContent='Спочатку скажи або напиши подію.';$('saveEvent').disabled=true;$('journalMsg').textContent='Записую…';try{await api({api:'timeline'},{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,event_type:eventType,input_mode:'web'})});$('eventText').value='';$('journalMsg').textContent='✓ Записано в HealthLab Timeline';await Promise.all([loadTimeline(),loadStateEvents()]);renderStateLab()}catch(e){$('journalMsg').textContent='Помилка: '+e.message}finally{$('saveEvent').disabled=false}}
async function loadTimeline(){try{const rs=await api({api:'timeline',limit:50});$('timelineRows').innerHTML=rs.length?rs.map(r=>`<div class="row-card"><div class="timeline-event-time">${esc(r.event_type||'подія')} · ${fmt(new Date(r.occurred_at).getTime())}</div><div class="timeline-event-title">${esc(r.title)}</div></div>`).join(''):'<div class="status">Подій ще немає</div>'}catch(e){$('timelineRows').innerHTML='<div class="status">'+esc(e.message)+'</div>'}}
function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('journalMsg').textContent='Цей браузер не дав доступу до розпізнавання голосу. Можна використати мікрофон клавіатури.';return}const r=new SR();r.lang='uk-UA';r.interimResults=false;r.maxAlternatives=1;$('journalMsg').textContent='Слухаю…';r.onresult=e=>{$('eventText').value=e.results[0][0].transcript;$('journalMsg').textContent='Перевір текст і натисни «Записати».'};r.onerror=e=>$('journalMsg').textContent='Мікрофон: '+e.error;r.start()}

async function loadHr(){const start=windowStart(),now=Date.now();const h=await api({api:'hr5m',from:Math.floor(start/1000),to:Math.floor(now/1000)});allHr=(Array.isArray(h)?h:[]).map(x=>({ts:epochMs(x.bucket),bpm:+x.bpm})).filter(x=>x.ts&&x.bpm>0).sort((a,b)=>a.ts-b.ts)}
async function loadDailyMetric(){const d=await api({api:'table',name:'dailyMetric',limit:2}),rows=Array.isArray(d)?d:(d.rows||[]),m=rows[0]||null;if(!m){$('hrvToday').textContent='—';$('respToday').textContent='—';return}const h=Number(m.avgHrv),r=Number(m.respRateBpm);$('hrvToday').textContent=Number.isFinite(h)?Math.round(h):'—';$('respToday').textContent=Number.isFinite(r)?r.toFixed(1):'—';const label=m.day?new Date(m.day+'T12:00:00').toLocaleDateString('uk-UA',{day:'2-digit',month:'2-digit',year:'numeric'}):'last night';$('hrvDay').textContent='WHOOP · ніч '+label;$('respDay').textContent='WHOOP · ніч '+label}
async function loadState(){const start=windowStart(),now=Date.now();const rs=await api({api:'state',from:Math.floor(start/1000),to:Math.floor(now/1000),bucket:300});stateRows=(Array.isArray(rs)?rs:[]).map(r=>({ts:epochMs(r.bucket_ts),avgHr:num(r.avg_hr),minHr:num(r.min_hr),maxHr:num(r.max_hr),motion:num(r.motion_score),rrCount:Number(r.rr_count||0),rmssd:num(r.rmssd_ms),sleep:r.sleep_state==='SLEEP'})).filter(r=>r.ts).sort((a,b)=>a.ts-b.ts)}
async function loadStateEvents(){try{const rs=await api({api:'timeline',limit:100});const start=windowStart();stateEvents=(Array.isArray(rs)?rs:[]).map(e=>({...e,ts:new Date(e.occurred_at).getTime()})).filter(e=>Number.isFinite(e.ts)&&e.ts>=start).sort((a,b)=>a.ts-b.ts)}catch{stateEvents=[]}}

function classifyStateRows(){if(!stateRows.length)return;const motions=stateRows.map(r=>r.motion).filter(v=>Number.isFinite(v)&&v>0).sort((a,b)=>a-b);const q25=quantile(motions,.25),q75=quantile(motions,.75);let th=(Number.isFinite(q25)&&Number.isFinite(q75))?Math.sqrt(Math.max(q25,1e-6)*Math.max(q75,1e-6)):.02;th=Math.max(.005,Math.min(.05,th));const quiet=stateRows.filter(r=>!r.sleep&&Number.isFinite(r.avgHr)&&Number.isFinite(r.motion)&&r.motion<th);const baselineHr=median(quiet.map(r=>r.avgHr));const validQuietHrv=quiet.filter(validHrv).map(r=>r.rmssd);const baselineRmssd=median(validQuietHrv);stateModel={movementThreshold:th,baselineHr,baselineRmssd};
  let lastActive=-Infinity;
  stateRows.forEach((r,i)=>{
    if(r.sleep){assign(r,'SLEEP',.98,'WHOOP sleep session перекриває це 5-хв вікно.');return}
    if(!Number.isFinite(r.avgHr)||!Number.isFinite(r.motion)){assign(r,'UNKNOWN',.15,'Немає одночасно HR + motion; HealthLab не вигадує стан.');return}
    if(r.motion>=th){lastActive=i;const c=Math.min(.98,.65+.25*Math.min(1,r.motion/Math.max(th,.0001)));assign(r,'MOVEMENT',c,`Motion ${r.motion.toFixed(4)} ≥ персонального порога ${th.toFixed(4)}.`);return}
    const ageMin=Number.isFinite(lastActive)?(i-lastActive)*5:Infinity;const residual=Number.isFinite(baselineHr)?r.avgHr-baselineHr:null;r.residual=residual;r.hrvValid=validHrv(r);r.context=findContext(r.ts);
    if(ageMin<=30||(ageMin<=120&&Number.isFinite(residual)&&residual>8)){assign(r,'RECOVERY',ageMin<=30?.85:.65,`Поточний рух низький, але фізична активність була ~${Math.round(ageMin)} хв тому${Number.isFinite(residual)?`; HR residual ${signed(residual)} bpm`:''}.`);return}
    const hrvSupp=(r.hrvValid&&Number.isFinite(baselineRmssd)&&baselineRmssd>0)?(baselineRmssd-r.rmssd)/baselineRmssd:null;
    if(Number.isFinite(residual)&&residual>=12&&((Number.isFinite(hrvSupp)&&hrvSupp>=.15)||(!r.hrvValid&&residual>=16))){let conf=r.hrvValid?Math.min(.9,.62+Math.max(0,hrvSupp)*.35):.55;let why=`Рух низький; HR ${signed(residual)} bpm проти quiet baseline`+(r.hrvValid?`; RMSSD ${Math.round(r.rmssd)} ms (${Math.round(hrvSupp*100)}% нижче quiet baseline).`:'; HRV-вікно недостатньої якості.');if(r.context?.kind==='POST_MEAL'){conf=Math.min(conf,.72);why+=' Є POST_MEAL контекст — це autonomic load, не доказ психологічного стресу.'}assign(r,'AUTONOMIC_LOAD',conf,why);return}
    const hq=r.hrvValid?'RR/HRV валідні':'HRV quality gate не пройдено';assign(r,'REST',r.hrvValid?.82:.65,`Рух низький; HR близький до quiet baseline${Number.isFinite(residual)?` (${signed(residual)} bpm)`:''}; ${hq}.`)
  })
}
function assign(r,state,confidence,reason){r.state=state;r.confidence=confidence;r.reason=reason;if(!r.context)r.context=findContext(r.ts);if(r.residual===undefined&&Number.isFinite(stateModel.baselineHr)&&Number.isFinite(r.avgHr))r.residual=r.avgHr-stateModel.baselineHr;r.hrvValid=validHrv(r)}
function validHrv(r){return r.rrCount>=100&&Number.isFinite(r.rmssd)&&r.rmssd>=5&&r.rmssd<=250}
function findContext(ts){let latest=null;for(const e of stateEvents){if(e.ts>ts)break;if(['food','meal_start','meal_end'].includes(e.event_type)&&ts-e.ts<=3*3600000)latest=e}if(latest&&latest.event_type!=='meal_end')return{kind:'POST_MEAL',label:`POST_MEAL · +${Math.round((ts-latest.ts)/60000)} хв`};return null}
function quantile(a,q){if(!a.length)return null;const p=(a.length-1)*q,b=Math.floor(p),d=p-b;return a[b+1]!==undefined?a[b]+d*(a[b+1]-a[b]):a[b]}
function median(a){const x=a.filter(Number.isFinite).sort((a,b)=>a-b);return quantile(x,.5)}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function signed(v){return `${v>=0?'+':''}${Math.round(v)}`}

function renderStateLab(){classifyStateRows();if(!stateRows.length){$('stateNow').textContent='UNKNOWN';$('stateReason').textContent='Ще немає State Engine даних у вибраному вікні.';$('stateStrip').innerHTML='';return}renderStateStrip();renderSignalChart('motionChart',stateRows.map(r=>({ts:r.ts,v:r.motion})),stateModel.movementThreshold,'motion');renderSignalChart('hrvChart',stateRows.filter(r=>r.hrvValid).map(r=>({ts:r.ts,v:r.rmssd})),stateModel.baselineRmssd,'hrv');renderStateEvents();selectState(stateRows.length-1);$('motionThreshold').textContent=`threshold ${stateModel.movementThreshold.toFixed(4)}`}
function renderStateStrip(){const groups=[];stateRows.forEach((r,i)=>{const g=groups.at(-1);if(g&&g.state===r.state){g.count++;g.end=i}else groups.push({state:r.state,start:i,end:i,count:1})});$('stateStrip').innerHTML='';groups.forEach(g=>{const b=document.createElement('button');const m=STATE_META[g.state]||STATE_META.UNKNOWN;b.className='state-segment '+m.cls;b.style.flexGrow=g.count;b.title=`${m.label} · ${fmtClock(stateRows[g.start].ts)}–${fmtClock(stateRows[g.end].ts)}`;b.onclick=()=>selectState(g.end);$('stateStrip').appendChild(b)})}
function selectState(i){const r=stateRows[i],m=STATE_META[r.state]||STATE_META.UNKNOWN;$('stateNow').textContent=m.label;$('stateDot').className='state-dot '+m.cls;$('stateConfidence').textContent=Math.round((r.confidence||0)*100)+'%';$('stateContext').textContent='Контекст: '+(r.context?.label||'—')+' · '+fmtClock(r.ts);$('stateReason').textContent=r.reason||'—';$('stateHr').textContent=Number.isFinite(r.avgHr)?Math.round(r.avgHr):'—';$('stateResidual').textContent=Number.isFinite(r.residual)?signed(r.residual):'—';$('stateRmssd').textContent=r.hrvValid?Math.round(r.rmssd):'—';$('stateMotion').textContent=Number.isFinite(r.motion)?r.motion.toFixed(4):'—';$('stateRrQuality').textContent=`RR ${r.rrCount} · ${r.hrvValid?'GOOD':'LIMITED'}`;const q=Number.isFinite(r.motion)?(r.hrvValid?'GOOD':'LIMITED'):'BAD';$('stateQuality').textContent='DATA '+q;$('stateQuality').className='badge '+(q==='GOOD'?'live':q==='LIMITED'?'warn':'bad')}
function renderStateEvents(){const box=$('stateEvents');if(!stateEvents.length){box.innerHTML='<span class="muted">Поки немає маркерів у вибраному вікні.</span>';return}box.innerHTML=stateEvents.slice(-24).map(e=>`<button class="event-chip" title="${esc(e.title)}"><b>${fmtClock(e.ts)}</b> ${esc(e.title)}</button>`).join('')}
function renderSignalChart(id,pts,reference,kind){const c=$(id),dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);if(!pts.length)return;const start=windowStart(),end=Date.now(),vals=pts.map(p=>p.v).filter(Number.isFinite);if(!vals.length)return;let lo=Math.min(...vals),hi=Math.max(...vals);if(Number.isFinite(reference)){lo=Math.min(lo,reference);hi=Math.max(hi,reference)}if(hi===lo){hi+=1;lo-=1}const pad=7;x.strokeStyle='#343b43';x.lineWidth=1;for(let i=1;i<3;i++){const y=h*i/3;x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke()}if(Number.isFinite(reference)){const y=pad+(hi-reference)/(hi-lo)*(h-2*pad);x.strokeStyle=kind==='motion'?'#e5bb55':'#7d879a';x.setLineDash([5,5]);x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke();x.setLineDash([])}x.strokeStyle=kind==='motion'?'#62c9a8':'#a78bfa';x.lineWidth=2;x.beginPath();let started=false;pts.forEach(p=>{if(!Number.isFinite(p.v))return;const px=(p.ts-start)/(end-start)*w,py=pad+(hi-p.v)/(hi-lo)*(h-2*pad);if(!started){x.moveTo(px,py);started=true}else x.lineTo(px,py)});x.stroke()}

function updateStatus(){$('status').textContent='HealthLab mirror · HR 5m: '+allHr.length+' · State 5m: '+stateRows.length+' · latest: '+(allHr.length?fmtClock(allHr.at(-1).ts):'—')+' · автооновлення 15 с'}
async function load(){try{const s0=await api({api:'summary'}),summary=Array.isArray(s0)?s0:(s0.tables||[]),map=new Map(summary.map(x=>[x.name||x.table,x]));$('rrCount').textContent=map.get('rrInterval')?.count||0;$('syncBadge').textContent=findNewest(summary)?'онлайн':'очікування';$('syncBadge').classList.toggle('live',!!findNewest(summary));$('totalRows').textContent=summary.reduce((a,x)=>a+(+x.count||0),0).toLocaleString('uk-UA')+' рядків';renderCards(map);await Promise.all([loadHr(),loadDailyMetric(),loadState(),loadStateEvents()]);renderPulse();renderStateLab();updateStatus()}catch(e){$('status').textContent='Помилка: '+e.message;$('stateReason').textContent='State Engine: '+e.message}}
function renderPulse(){const start=windowStart(),now=Date.now(),pts=allHr.filter(x=>x.ts>=start&&x.ts<=now),vals=pts.map(x=>x.bpm);$('pulseNow').textContent=vals.length?Math.round(vals.at(-1)):'—';$('minHr').textContent=vals.length?Math.round(Math.min(...vals)):'—';$('avgHr').textContent=vals.length?Math.round(vals.reduce((a,b)=>a+b,0)/vals.length):'—';$('maxHr').textContent=vals.length?Math.round(Math.max(...vals)):'—';$('periodCaption').textContent='5-minute average | '+(period==='today'?'since midnight':'last '+period+' hours');$('timeLeft').textContent=fmtClock(start);$('timeMid').textContent=fmtClock(start+(now-start)/2);draw(pts,start,now)}
function draw(pts,start,end){const c=$('pulseChart'),dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);$('chartEmpty').classList.toggle('hidden',pts.length>0);if(!pts.length)return;const vals=pts.map(p=>p.bpm),lo=Math.floor(Math.min(...vals)-2),hi=Math.ceil(Math.max(...vals)+2),pad=10;x.strokeStyle='#343b43';for(let i=0;i<4;i++){const y=pad+(h-2*pad)*i/3;x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke()}x.strokeStyle='#e96a32';x.lineWidth=2;x.beginPath();pts.forEach((p,i)=>{const px=(p.ts-start)/(end-start)*w,py=pad+(hi-p.bpm)/(hi-lo||1)*(h-2*pad);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}
function renderCards(map){const g=$('tableGrid');g.innerHTML='';TABLES.forEach(n=>{const q=map.get(n)||{},e=document.createElement('article');e.className='table-card';e.innerHTML=`<div class="table-name">${n}</div><div class="table-count">${(+q.count||0).toLocaleString('uk-UA')}</div>`;e.onclick=()=>openTable(n,q.count||0);g.appendChild(e)})}
async function openTable(n,count){$('viewerTitle').textContent=n;$('viewerMeta').textContent=count+' рядків · останні 100';$('viewer').classList.remove('hidden');const rs=await api({api:'table',name:n,limit:100});$('rows').innerHTML=rs.map(r=>`<div class="row-card">${Object.entries(r).filter(([k])=>!k.startsWith('_hl_')).map(([k,v])=>`<div class="kv"><b>${esc(k)}</b><span>${esc(typeof v==='object'?JSON.stringify(v):v)}</span></div>`).join('')}</div>`).join('')}
function findNewest(s){let z=0;s.forEach(x=>{const v=x.lastTs;if(v)z=Math.max(z,epochMs(v))});return z}
function fmtClock(t){return new Date(t).toLocaleTimeString('uk-UA',{hour:'2-digit',minute:'2-digit'})}
function fmt(v){return new Date(v).toLocaleString('uk-UA')}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
