(()=>{
  const API='https://ttvlgfzvgjcbomdlddbn.supabase.co/functions/v1/noop-db-viewer';
  const NEED_MIN=480;
  let sessions=[],metrics=[],series=[],stateRows=[],index=0,selected=null;
  const $=id=>document.getElementById(id);
  const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
  const epochMs=v=>{const n=Number(v);return Number.isFinite(n)?(n<1e12?n*1000:n):0};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const median=a=>{const x=a.filter(Number.isFinite).sort((a,b)=>a-b);if(!x.length)return null;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2};
  const mean=a=>{const x=a.filter(Number.isFinite);return x.length?x.reduce((s,v)=>s+v,0)/x.length:null};
  const fmtTime=s=>new Date(epochMs(s)).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});
  const fmtDate=s=>new Date(epochMs(s)).toLocaleDateString('en-GB',{weekday:'short',day:'2-digit',month:'short',year:'numeric'});
  const fmtDurMin=m=>{if(!Number.isFinite(m))return '—';m=Math.max(0,Math.round(m));return m<60?`${m}m`:`${Math.floor(m/60)}h ${String(m%60).padStart(2,'0')}m`};
  const fmtDurSec=s=>fmtDurMin(s/60);
  async function api(p,timeout=22000){const u=new URL(API);Object.entries(p).forEach(([k,v])=>u.searchParams.set(k,v));const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(u,{cache:'no-store',signal:c.signal});if(!r.ok)throw Error('HTTP '+r.status);const d=await r.json();if(d?.error)throw Error(d.error);return d}finally{clearTimeout(t)}}
  function rowsOf(d){return Array.isArray(d)?d:(Array.isArray(d?.rows)?d.rows:[])}
  function parseStages(v){try{const a=typeof v==='string'?JSON.parse(v):v;return (Array.isArray(a)?a:[]).map(x=>({start:Number(x.start),end:Number(x.end),stage:String(x.stage||'').toLowerCase()==='awake'?'wake':String(x.stage||'').toLowerCase()})).filter(x=>x.start>0&&x.end>x.start)}catch{return []}}
  function stageStats(s){const a=parseStages(s?.stagesJSON),o={light:0,deep:0,rem:0,wake:0};a.forEach(x=>{if(o[x.stage]!==undefined)o[x.stage]+=(x.end-x.start)/60});o.asleep=o.light+o.deep+o.rem;o.total=o.asleep+o.wake;o.segments=a;return o}
  function metricForDay(day){return metrics.find(x=>x.day===day)||null}
  function performanceForDay(day){const a=series.filter(x=>x.key==='sleep_performance'&&x.day===day).map(x=>num(x.value)).filter(Number.isFinite);return a.length?a[0]:null}
  function selectedDay(){return selected?new Date(epochMs(selected.endTs)).toLocaleDateString('en-CA'):null}
  function localMinutes(ts){const d=new Date(epochMs(ts));return d.getHours()*60+d.getMinutes()}
  function circDiff(a,b){let d=Math.abs(a-b)%1440;return Math.min(d,1440-d)}
  function latestMetrics(n=14){return metrics.filter(x=>num(x.totalSleepMin)!==null).slice(0,n).reverse()}
  function typical(field,excludeDay=null){return mean(metrics.filter(x=>!excludeDay||x.day!==excludeDay).slice(0,14).map(x=>num(x[field])).filter(Number.isFinite))}
  function restWord(score){return !Number.isFinite(score)?'Sleep':score<50?'Poor':score<70?'Fair':score<85?'Good':'Optimal'}
  function pct(v){return Number.isFinite(v)?`${Math.round(v)}%`:'—'}
  function colorStage(k){return ({deep:'#5d52ca',light:'#4d9ff0',rem:'#bb82ec',wake:'#f29a57'})[k]||'#677082'}

  function openModal(title,html){$('sleepModalTitle').textContent=title;$('sleepModalBody').innerHTML=html;$('sleepModal').classList.remove('hidden')}
  function closeModal(){$('sleepModal').classList.add('hidden')}
  function safeWrite(title,detail){openModal(title,`<p>${esc(detail)}</p><div class="sleep-readonly-note"><b>HealthLab Web mirror is read-only for this Android action.</b><br>This action changes Android Room / WHOOP-side state. It is intentionally not sent through the current public viewer. A protected authenticated write bridge is required first.</div><div class="sleep-action-row"><button data-modal-close>Close</button></div>`)}

  async function load(){
    $('sleepRefresh').classList.add('busy');$('sleepStatus').textContent='Loading Android Sleep mirror…';
    try{
      const [ss,dm,ms]=await Promise.all([api({api:'sleepSessions',limit:90}),api({api:'table',name:'dailyMetric',limit:90}),api({api:'table',name:'metricSeries',limit:500})]);
      sessions=rowsOf(ss).filter(s=>num(s.startTs)&&num(s.endTs)>num(s.startTs)).sort((a,b)=>num(b.endTs)-num(a.endTs));
      metrics=rowsOf(dm).sort((a,b)=>String(b.day||'').localeCompare(String(a.day||'')));
      series=rowsOf(ms);
      index=Math.min(index,Math.max(0,sessions.length-1));selected=sessions[index]||null;
      await loadState();render();maybeJournal();
      $('sleepStatus').textContent=selected?`Android Sleep mirror · ${sessions.length} sleep sessions loaded · read-only web actions`:'No completed sleep sessions.';
    }catch(e){$('sleepStatus').textContent='Sleep mirror error: '+(e?.message||e)}finally{$('sleepRefresh').classList.remove('busy')}
  }
  async function loadState(){stateRows=[];if(!selected)return;try{const d=await api({api:'state',from:Math.floor(num(selected.startTs)),to:Math.floor(num(selected.endTs)),bucket:300},35000);stateRows=rowsOf(d).map(r=>({ts:epochMs(r.bucket_ts),motion:num(r.motion_score),hr:num(r.avg_hr),rr:Number(r.rr_count||0),rmssd:num(r.rmssd_ms)})).filter(r=>r.ts).sort((a,b)=>a.ts-b.ts)}catch{stateRows=[]}}
  async function navigate(i){if(i<0||i>=sessions.length)return;index=i;selected=sessions[index];await loadState();render()}

  function render(){renderHero();renderNight();renderMetrics();renderDebt();renderTypical();renderTrends();renderNeeded();renderConsistency()}
  function renderHero(){if(!selected){$('restScore').textContent='—';return}const day=selectedDay(),m=metricForDay(day),st=stageStats(selected),score=performanceForDay(day);$('restScore').textContent=Number.isFinite(score)?Math.round(score):'—';$('restUnit').textContent=Number.isFinite(score)?'%':'';$('restFill').style.height=`${Math.max(8,Math.min(100,score||0))}%`;$('restWord').textContent=restWord(score);$('restSource').textContent=Number.isFinite(score)?'On-device':'Sleep session';$('restAsleep').textContent=`${fmtDurMin(num(m?.totalSleepMin)??st.asleep)} asleep`}
  function renderNight(){if(!selected)return;const st=stageStats(selected),eff=(num(selected.efficiency)??num(metricForDay(selectedDay())?.efficiency));$('nightLabel').textContent=index===0?'Last night':index===1?'1 night ago':`${index} nights ago`;$('nightDate').textContent=fmtDate(selected.endTs);$('nightClock').textContent=`${fmtTime(selected.startTs)} – ${fmtTime(selected.endTs)}`;$('fellAsleep').textContent=fmtTime(selected.startTs);$('wokeAt').textContent=fmtTime(selected.endTs);$('stageSubtitle').textContent=`${fmtDurSec(num(selected.endTs)-num(selected.startTs))} in bed · ${Number.isFinite(eff)?Math.round(eff*100)+'%':'—'} efficiency`;$('stageAsleep').textContent=fmtDurMin(st.asleep);$('axisStart').textContent=fmtTime(selected.startTs);$('axisMid').textContent=fmtTime((num(selected.startTs)+num(selected.endTs))/2);$('axisEnd').textContent=fmtTime(selected.endTs);$('prevNight').disabled=index>=sessions.length-1;$('nextNight').disabled=index<=0;$('olderHint').classList.toggle('hidden',sessions.length>1||index>0);renderHypnogram(st);renderMotion();renderNaps()}
  function renderHypnogram(st){const box=$('hypnogram');box.innerHTML=st.segments.map(x=>`<span class="${esc(x.stage)}" style="flex:${Math.max(1,x.end-x.start)}" title="${esc(x.stage)} · ${fmtTime(x.start)}–${fmtTime(x.end)}"></span>`).join('');const order=['rem','deep','light','wake'];$('stageRows').innerHTML=order.map(k=>{const v=st[k],p=st.total?Math.round(v/st.total*100):0;return `<div class="sleep-stage-row"><span>${k==='wake'?'AWAKE':k.toUpperCase()}</span><em style="color:${colorStage(k)}">${p}%</em><div class="sleep-stage-tube"><div class="sleep-stage-pip ${k}" style="width:${p}%"></div></div><b>${fmtDurMin(v)}</b></div>`}).join('')}
  function renderMotion(){const c=$('motionStrip'),ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth||500,h=c.clientHeight||58;c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(255,255,255,.09)';ctx.beginPath();ctx.moveTo(0,h-1);ctx.lineTo(w,h-1);ctx.stroke();const vals=stateRows.map(r=>r.motion).filter(Number.isFinite);if(vals.length<2)return;const max=Math.max(...vals,1e-9);ctx.strokeStyle='#8b84ff';ctx.fillStyle='rgba(139,132,255,.18)';ctx.beginPath();vals.forEach((v,i)=>{const x=i/(vals.length-1)*w,y=h-2-(v/max)*(h-5);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.lineTo(w,h);ctx.lineTo(0,h);ctx.closePath();ctx.fill();ctx.beginPath();vals.forEach((v,i)=>{const x=i/(vals.length-1)*w,y=h-2-(v/max)*(h-5);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
  function renderNaps(){$('napSummary').classList.add('hidden');$('napRows').innerHTML='<p class="sleep-muted">No naps recorded for this day.</p>';$('sleepSourceBadge').textContent='Whoop';$('whySleepReason').textContent='This is your only sleep block today.'}

  function buildSeries(){const rev=metrics.filter(x=>num(x.totalSleepMin)!==null).slice(0,30).reverse();return rev.map(m=>{const sleep=num(m.totalSleepMin),eff=num(m.efficiency),rest=performanceForDay(m.day),restorative=(num(m.deepMin)||0)+(num(m.remMin)||0),restPct=Number.isFinite(sleep)&&sleep>0?restorative/sleep*100:null,need=NEED_MIN,hoursNeed=Number.isFinite(sleep)?sleep/need*100:null,debt=Number.isFinite(sleep)?Math.max(0,need-sleep):null;return{day:m.day,rest,eff:Number.isFinite(eff)?eff*100:null,hoursNeed,restorative:restPct,resp:num(m.respRateBpm),debt,sleep}})}
  function consistencyNow(){const recent=sessions.slice(0,14);if(recent.length<3)return null;const beds=recent.map(s=>localMinutes(s.startTs)),wakes=recent.map(s=>localMinutes(s.endTs)),tb=median(beds),tw=median(wakes),ok=recent.filter(s=>circDiff(localMinutes(s.startTs),tb)<=45&&circDiff(localMinutes(s.endTs),tw)<=45).length;return ok/recent.length*100}
  function renderMetrics(){const arr=buildSeries(),last=arr.at(-1)||{},map=[['performance','Rest',last.rest,'%'],['efficiency','Efficiency',last.eff,'%'],['consistency','Consistency',consistencyNow(),'%'],['hours_needed','Hours vs Needed',last.hoursNeed,'%'],['restorative','Restorative',last.restorative,'%'],['resp','Respiratory',last.resp,' rpm'],['debt','Sleep Debt',last.debt,'m']];$('metricGrid').innerHTML=map.map(([k,label,v,u])=>{const hist=metricHistory(k,arr),typ=mean(hist.slice(0,-1)),cap=Number.isFinite(v)&&Number.isFinite(typ)?`${v>=typ?'+':''}${Math.round(v-typ)}${u.trim()} vs typical`:'—';const val=k==='debt'?fmtDurMin(v):Number.isFinite(v)?(k==='resp'?v.toFixed(1):Math.round(v))+u:'—';return `<article class="sleep-card sleep-metric-tile" data-metric="${k}"><span>${label}</span><strong>${val}</strong><small>${cap}</small><canvas class="sleep-metric-spark" data-spark="${k}" height="28"></canvas></article>`}).join('');requestAnimationFrame(()=>{document.querySelectorAll('[data-spark]').forEach(c=>drawMini(c,metricHistory(c.dataset.spark,arr)));document.querySelectorAll('[data-metric]').forEach(e=>e.onclick=()=>openMetricDetail(e.dataset.metric))})}
  function metricHistory(k,arr=buildSeries()){if(k==='consistency')return sessions.slice(0,14).reverse().map((_,i,a)=>{const subset=sessions.slice(0,a.length-i);if(subset.length<3)return null;const b=subset.map(s=>localMinutes(s.startTs)),w=subset.map(s=>localMinutes(s.endTs)),tb=median(b),tw=median(w);return subset.filter(s=>circDiff(localMinutes(s.startTs),tb)<=45&&circDiff(localMinutes(s.endTs),tw)<=45).length/subset.length*100}).filter(Number.isFinite);const key=({performance:'rest',efficiency:'eff',hours_needed:'hoursNeed',restorative:'restorative',resp:'resp',debt:'debt'})[k];return arr.map(x=>x[key]).filter(Number.isFinite)}
  function drawMini(c,vals){const ctx=c.getContext('2d'),w=c.clientWidth||120,h=c.clientHeight||28,dpr=devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);if(vals.length<2)return;const lo=Math.min(...vals),hi=Math.max(...vals),span=hi-lo||1;ctx.strokeStyle='#8b84ff';ctx.lineWidth=1.6;ctx.beginPath();vals.forEach((v,i)=>{const x=i/(vals.length-1)*w,y=h-2-(v-lo)/span*(h-4);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
  function openMetricDetail(k){const names={performance:['Rest','%'],efficiency:['Sleep Efficiency','%'],consistency:['Consistency','%'],hours_needed:['Hours vs Needed','%'],restorative:['Restorative','%'],resp:['Respiratory',' rpm'],debt:['Sleep Debt','m']},[title,unit]=names[k]||[k,''];openModal(title,`<div id="metricDetailValue" class="sleep-detail-value">—</div><div class="sleep-range">${['W','M','3M','6M','1Y','ALL'].map(r=>`<button data-range="${r}" class="${r==='M'?'active':''}">${r}</button>`).join('')}</div><canvas id="metricDetailCanvas" class="sleep-detail-canvas" height="220"></canvas><div id="metricDetailNote" class="sleep-muted"></div>`);const draw=r=>{const days={W:7,M:30,'3M':90,'6M':180,'1Y':365,ALL:9999}[r],a=metricHistory(k).slice(-days),v=a.at(-1);$('metricDetailValue').textContent=k==='debt'?fmtDurMin(v):Number.isFinite(v)?(k==='resp'?v.toFixed(1):Math.round(v))+unit:'—';drawChart($('metricDetailCanvas'),a,false);$('metricDetailNote').textContent=a.length<2?'Not enough history in this range. Try 3M, 6M, or ALL.':`${a.length} data points in ${r}.`};draw('M');document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-range]').forEach(x=>x.classList.toggle('active',x===b));draw(b.dataset.range)})}

  function renderDebt(){const a=latestMetrics(14),d=a.map(m=>({day:m.day,delta:(num(m.totalSleepMin)||0)-NEED_MIN})),bal=d.reduce((s,x)=>s+x.delta,0),def=bal<0;$('debtLedger').innerHTML=`<div class="sleep-ledger-head"><strong>${def?'-':'+'}${fmtDurMin(Math.abs(bal))}</strong><b style="color:${def?'#f07872':'#74d9a4'}">${def?'sleep debt':bal>0?'surplus':'balanced'}</b></div><div class="sleep-ledger-copy">${def?'Your recent nights add up to a sleep deficit.':'Your recent nights are at or above the current on-device need reference.'}</div><div class="sleep-delta-bars">${d.map(x=>{const max=Math.max(...d.map(y=>Math.abs(y.delta)),1),h=Math.max(2,Math.abs(x.delta)/max*28),top=x.delta>=0?30-h:31;return `<span title="${esc(x.day)} ${Math.round(x.delta)}m"><i class="${x.delta<0?'deficit':''}" style="height:${h}px;top:${top}px"></i></span>`}).join('')}</div><div class="sleep-stat-footer"><div><span>BALANCE</span><b>${bal>=0?'+':''}${fmtDurMin(Math.abs(bal))}</b></div><div><span>PER-NIGHT NEED</span><b>${fmtDurMin(NEED_MIN)}</b></div><div><span>NIGHTS</span><b>${d.length}</b></div></div>`}
  function renderTypical(){const day=selectedDay(),m=metricForDay(day),rows=[['Deep',num(m?.deepMin),typical('deepMin',day),'deep'],['REM',num(m?.remMin),typical('remMin',day),'rem'],['Light',num(m?.lightMin),typical('lightMin',day),'light']];$('stagesTypical').innerHTML=rows.map(([label,v,t,k])=>{const max=Math.max(v||0,t||0,1)*1.18,p=Number.isFinite(v)?Math.min(100,v/max*100):0,mp=Number.isFinite(t)?Math.min(100,t/max*100):0,d=Number.isFinite(v)&&Number.isFinite(t)?`${v>=t?'+':'−'}${fmtDurMin(Math.abs(v-t))} vs typ`:'';return `<div class="sleep-typical-row"><div class="sleep-typical-head"><span>${label}</span><span><b>${fmtDurMin(v)}</b> <small>${d}</small></span></div><div class="sleep-typical-track"><div class="sleep-typical-fill" style="width:${p}%;background:${colorStage(k)}"></div>${Number.isFinite(t)?`<i class="sleep-typical-marker" style="left:${mp}%"></i>`:''}</div></div>`}).join('')}
  function renderTrends(){const a=latestMetrics(14),hrs=a.map(x=>num(x.totalSleepMin)/60).filter(Number.isFinite),deb=a.map(x=>Math.max(0,NEED_MIN-(num(x.totalSleepMin)||0))/60);$('hoursAvg').textContent=hrs.length?mean(hrs).toFixed(1)+' h avg':'—';$('debtNow').textContent=deb.length?deb.at(-1).toFixed(1)+' h':'—';drawChart($('hoursTrend'),hrs,false);drawChart($('debtTrend'),deb,true);$('hoursFooter').innerHTML=foot([['AVG',mean(hrs)?.toFixed(1)+' h'],['MIN',hrs.length?Math.min(...hrs).toFixed(1)+' h':'—'],['MAX',hrs.length?Math.max(...hrs).toFixed(1)+' h':'—'],['NIGHTS',hrs.length]]);$('debtFooter').innerHTML=foot([['AVG',mean(deb)?.toFixed(1)+' h'],['MAX',deb.length?Math.max(...deb).toFixed(1)+' h':'—'],['DAYS',deb.length]])}
  function drawChart(c,vals,bars=false){if(!c)return;const ctx=c.getContext('2d'),w=c.clientWidth||540,h=c.clientHeight||190,dpr=devicePixelRatio||1;c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(255,255,255,.08)';for(let i=1;i<4;i++){const y=i*h/4;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}if(!vals.length)return;const lo=bars?0:Math.min(...vals),hi=Math.max(...vals),span=hi-lo||1;if(bars){const slot=w/vals.length;vals.forEach((v,i)=>{const bh=(v-lo)/span*(h-12),x=i*slot+slot*.18;ctx.fillStyle='rgba(197,111,139,.82)';ctx.fillRect(x,h-bh-4,slot*.64,bh)})}else{ctx.strokeStyle='#8b84ff';ctx.lineWidth=2;ctx.beginPath();vals.forEach((v,i)=>{const x=vals.length===1?w/2:i/(vals.length-1)*w,y=h-7-(v-lo)/span*(h-20);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}}
  function foot(items){return items.map(([a,b])=>`<div><span>${a}</span><b>${b??'—'}</b></div>`).join('')}
  function renderNeeded(){const m=metricForDay(selectedDay()),slept=num(m?.totalSleepMin),need=NEED_MIN,p=Number.isFinite(slept)?slept/need*100:null,debt=Number.isFinite(slept)?Math.max(0,need-slept):null;$('hoursNeededPct').textContent=pct(p);$('hoursNeededCard').innerHTML=`<div class="sleep-needed-main"><strong>${fmtDurMin(slept)}</strong><span>of ${fmtDurMin(need)} needed</span></div><div class="sleep-need-track"><i style="width:${Math.min(100,p||0)}%"></i></div><div class="sleep-need-components"><i style="width:75%"></i><i style="width:12.5%"></i><i style="width:12.5%"></i></div><div class="sleep-need-labels"><span>Healthy Minimum</span><span>Strain buffer</span><span>Debt repayment</span></div><div class="sleep-stat-footer"><div><span>SLEPT</span><b>${fmtDurMin(slept)}</b></div><div><span>NEEDED</span><b>${fmtDurMin(need)}</b></div><div><span>DEBT</span><b>${fmtDurMin(debt)}</b></div></div><div class="sleep-readonly-note">Need components use the same web-mirror fallback reference of 8h when NOOP's imported sleep_need_min series is not present.</div>`}
  function renderConsistency(){const recent=sessions.slice(0,14).reverse();if(recent.length<3){$('consistencySection').classList.add('hidden');return}$('consistencySection').classList.remove('hidden');const beds=recent.map(s=>localMinutes(s.startTs)),wakes=recent.map(s=>localMinutes(s.endTs)),tb=median(beds),tw=median(wakes),score=recent.filter(s=>circDiff(localMinutes(s.startTs),tb)<=45&&circDiff(localMinutes(s.endTs),tw)<=45).length/recent.length*100;$('consistencyScore').textContent=Math.round(score)+'%';drawConsistency($('consistencyChart'),recent,tb,tw);$('consistencyFooter').innerHTML=foot([['SCORE',Math.round(score)+'%'],['TYP BED',minutesLabel(tb)],['TYP WAKE',minutesLabel(tw)],['NIGHTS',recent.length]])}
  function minutesLabel(m){if(!Number.isFinite(m))return'—';m=Math.round(m)%1440;return`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`}
  function drawConsistency(c,ss,tb,tw){const ctx=c.getContext('2d'),w=c.clientWidth||540,h=c.clientHeight||220,dpr=devicePixelRatio||1;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const times=ss.flatMap(s=>[localMinutes(s.startTs),localMinutes(s.endTs)]),norm=m=>{let x=m;if(x<720)x+=1440;return x},lo=Math.min(...times.map(norm),norm(tb))-60,hi=Math.max(...times.map(norm),norm(tw))+60,span=hi-lo||1,y=v=>(norm(v)-lo)/span*(h-24)+12;ctx.strokeStyle='rgba(255,255,255,.08)';for(let i=0;i<4;i++){const yy=12+i*(h-24)/3;ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(w,yy);ctx.stroke()}const slot=w/ss.length;ss.forEach((s,i)=>{const x=i*slot+slot/2,y1=y(localMinutes(s.startTs)),y2=y(localMinutes(s.endTs));ctx.strokeStyle='#8b84ff';ctx.lineWidth=Math.max(3,slot*.35);ctx.beginPath();ctx.moveTo(x,y1);ctx.lineTo(x,y2);ctx.stroke()});ctx.setLineDash([5,5]);ctx.lineWidth=1;ctx.strokeStyle='#f0c66b';[tb,tw].forEach(v=>{const yy=y(v);ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(w,yy);ctx.stroke()});ctx.setLineDash([])}
  function maybeJournal(){if(!selected)return;const ago=(Date.now()-epochMs(selected.endTs))/3600000,day=new Date().toLocaleDateString('en-CA'),key='hl_sleep_journal_'+day;if(ago>=0&&ago<=12&&!sessionStorage.getItem(key))$('journalPrompt').classList.remove('hidden')}
  function openDatePicker(){const current=selectedDay();openModal('Pick night date',`<div class="sleep-form-row"><label>DATE</label><input id="nightDateInput" type="date" max="${new Date().toLocaleDateString('en-CA')}" value="${current||''}"></div><div class="sleep-action-row"><button id="applyNightDate">Open this night</button></div>`);$('applyNightDate').onclick=()=>{const d=$('nightDateInput').value,i=sessions.findIndex(s=>new Date(epochMs(s.endTs)).toLocaleDateString('en-CA')===d);if(i<0){$('applyNightDate').textContent='No stored sleep on this date';return}closeModal();navigate(i)}}
  function openEdit(){openModal('Adjust sleep times',`<p>Choose which end of the night to adjust.</p><div class="sleep-action-row"><button id="chooseBed"><small>BEDTIME</small><br><b>${fmtTime(selected.startTs)}</b> ✎</button><button id="chooseWake"><small>WAKE-UP</small><br><b>${fmtTime(selected.endTs)}</b> ✎</button></div>`);$('chooseBed').onclick=()=>openTimeAction('Bedtime',fmtTime(selected.startTs));$('chooseWake').onclick=()=>openTimeAction('Wake-up time',fmtTime(selected.endTs))}
  function openTimeAction(title,value){openModal(title,`<div class="sleep-form-row"><label>${esc(title.toUpperCase())}</label><input id="sleepTimeInput" type="time" value="${value}"></div><div class="sleep-action-row"><button id="sleepTimeContinue">Save</button></div>`);$('sleepTimeContinue').onclick=()=>safeWrite('Move this sleep?','This mirrors Android’s guarded sleep-time editor. The selected time is not written from the public web mirror.')}
  function confirmDelete(){openModal('Delete this sleep session?',`<p>Removes this recorded sleep and recomputes the day without it. Android can also prevent re-detection in this window and offers Undo for a few seconds.</p><div class="sleep-action-row"><button id="confirmDelete" class="danger">Delete</button><button data-modal-close>Cancel</button></div>`);$('confirmDelete').onclick=()=>safeWrite('Delete blocked in web mirror','Deletion is intentionally not sent through the current viewer endpoint. The Android app remains the authority for this mutation.')}
  function openAddNap(){openModal('Add a nap',`<div class="sleep-form-row"><label>NAP STARTED</label><input id="napStart" type="time"></div><div class="sleep-form-row"><label>NAP ENDED</label><input id="napEnd" type="time"></div><div class="sleep-action-row"><button id="saveNap">Add nap</button></div>`);$('saveNap').onclick=()=>safeWrite('Add nap blocked in web mirror','Android stages a manual nap from raw data and stores it as its own session. The web mirror will not create a partial or unauthenticated substitute.')}

  $('sleepModalClose').onclick=closeModal;$('sleepModal').addEventListener('click',e=>{if(e.target.dataset.closeModal!==undefined||e.target.dataset.modalClose!==undefined)closeModal()});
  $('sleepRefresh').onclick=load;$('prevNight').onclick=()=>navigate(index+1);$('nextNight').onclick=()=>navigate(index-1);$('pickNight').onclick=openDatePicker;$('editSleep').onclick=openEdit;$('deleteSleep').onclick=confirmDelete;$('addNap').onclick=openAddNap;$('whySleep').onclick=()=>$('whySleepText').classList.toggle('hidden');
  $('markBed').onclick=()=>safeWrite('Going to sleep','Android logs a BEDTIME sleep_mark with the current time and also appends it to the shareable strap log.');$('markWake').onclick=()=>safeWrite("I'm awake",'Android logs a WAKE sleep_mark with the current time and also appends it to the shareable strap log.');$('openJournal').onclick=()=>{sessionStorage.setItem('hl_sleep_journal_'+new Date().toLocaleDateString('en-CA'),'1');location.href='./index.html#events'};$('laterJournal').onclick=()=>{sessionStorage.setItem('hl_sleep_journal_'+new Date().toLocaleDateString('en-CA'),'1');$('journalPrompt').classList.add('hidden')};
  load();window.addEventListener('resize',()=>{if(selected){renderMotion();renderTrends();renderConsistency()}});
})();
